-- =============================================
-- SCHEMA COMPLETO - GSG Dashboard
-- =============================================
-- Base de datos completa con TODAS las tablas
-- =============================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-------------------------------------------------------------------------------
-- CATEGORIES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- FINISHES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.finishes (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  hex_color text CHECK (hex_color IS NULL OR hex_color ~ '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'::text),
  sheen text,
  texture text,
  material_base text,
  swatch_url text,
  display_order smallint DEFAULT 100,
  is_active boolean DEFAULT true,
  CONSTRAINT finishes_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- LIGHT TONES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.light_tones (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  kelvin integer,
  CONSTRAINT light_tones_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- ACCESSORIES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.accessories (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  photo_url text,
  watt numeric,
  voltage_label text,
  voltage_min integer,
  voltage_max integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT accessories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.accessory_finishes (
  accessory_id bigint NOT NULL,
  finish_id bigint NOT NULL,
  CONSTRAINT accessory_finishes_pkey PRIMARY KEY (accessory_id, finish_id),
  CONSTRAINT accessory_finishes_accessory_id_fkey FOREIGN KEY (accessory_id) REFERENCES public.accessories(id) ON DELETE CASCADE,
  CONSTRAINT accessory_finishes_finish_id_fkey FOREIGN KEY (finish_id) REFERENCES public.finishes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.accessory_light_tones (
  accessory_id bigint NOT NULL,
  light_tone_id bigint NOT NULL,
  CONSTRAINT accessory_light_tones_pkey PRIMARY KEY (accessory_id, light_tone_id),
  CONSTRAINT accessory_light_tones_accessory_id_fkey FOREIGN KEY (accessory_id) REFERENCES public.accessories(id) ON DELETE CASCADE,
  CONSTRAINT accessory_light_tones_light_tone_id_fkey FOREIGN KEY (light_tone_id) REFERENCES public.light_tones(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.accessory_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  accessory_id bigint NOT NULL,
  path text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['gallery'::text, 'tech'::text])),
  alt_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT accessory_media_pkey PRIMARY KEY (id),
  CONSTRAINT accessory_media_accessory_id_fkey FOREIGN KEY (accessory_id) REFERENCES public.accessories(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- LED DIFFUSERS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.led_diffusers (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  material text,
  uv_protection boolean DEFAULT false,
  CONSTRAINT led_diffusers_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- LED PROFILES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.led_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  material text,
  finish_surface text,
  max_w_per_m numeric,
  use_cases text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT led_profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.led_profile_diffusers (
  profile_id bigint NOT NULL,
  diffuser_id bigint NOT NULL,
  included_by_m boolean DEFAULT false,
  included_qty_per_m numeric DEFAULT 0,
  notes text,
  CONSTRAINT led_profile_diffusers_pkey PRIMARY KEY (profile_id, diffuser_id),
  CONSTRAINT led_profile_diffusers_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE,
  CONSTRAINT led_profile_diffusers_diffuser_id_fkey FOREIGN KEY (diffuser_id) REFERENCES public.led_diffusers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_profile_finishes (
  profile_id bigint NOT NULL,
  finish_id bigint NOT NULL,
  CONSTRAINT led_profile_finishes_pkey PRIMARY KEY (profile_id, finish_id),
  CONSTRAINT led_profile_finishes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE,
  CONSTRAINT led_profile_finishes_finish_id_fkey FOREIGN KEY (finish_id) REFERENCES public.finishes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_profile_included_items (
  profile_id bigint NOT NULL,
  accessory_id bigint NOT NULL,
  qty_per_m numeric NOT NULL DEFAULT 1,
  CONSTRAINT led_profile_included_items_pkey PRIMARY KEY (profile_id, accessory_id),
  CONSTRAINT led_profile_included_items_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE,
  CONSTRAINT led_profile_included_items_accessory_id_fkey FOREIGN KEY (accessory_id) REFERENCES public.accessories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_profile_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  profile_id bigint NOT NULL,
  path text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['cover'::text, 'gallery'::text, 'tech'::text, 'accessory'::text, 'datasheet'::text, 'spec'::text])),
  alt_text text,
  created_at timestamp with time zone DEFAULT now(),
  mime_type text,
  file_size_bytes bigint,
  title text,
  CONSTRAINT led_profile_media_pkey PRIMARY KEY (id),
  CONSTRAINT led_profile_media_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_profile_optional_items (
  profile_id bigint NOT NULL,
  accessory_id bigint NOT NULL,
  CONSTRAINT led_profile_optional_items_pkey PRIMARY KEY (profile_id, accessory_id),
  CONSTRAINT led_profile_optional_items_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE,
  CONSTRAINT led_profile_optional_items_accessory_id_fkey FOREIGN KEY (accessory_id) REFERENCES public.accessories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_profile_parts (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  profile_id bigint NOT NULL,
  name text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['included'::text, 'optional'::text])),
  qty_per_m numeric DEFAULT 0,
  notes text,
  photo_url text,
  display_order smallint DEFAULT 100,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT led_profile_parts_pkey PRIMARY KEY (id),
  CONSTRAINT led_profile_parts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.led_profiles(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- LED ROLLS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.led_rolls (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  typology text,
  color_control text,
  cri_min integer,
  voltage_v integer,
  ip_rating text,
  dimmable boolean DEFAULT true,
  dynamic_effects text,
  cut_step_mm_min integer,
  cut_step_mm_max integer,
  width_mm_min numeric,
  width_mm_max numeric,
  eff_lm_per_w_min numeric,
  eff_lm_per_w_max numeric,
  flux_lm_per_m_min numeric,
  flux_lm_per_m_max numeric,
  leds_per_m_min integer,
  leds_per_m_max integer,
  roll_length_m numeric DEFAULT 5,
  warranty_years integer DEFAULT 3,
  packaging text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT led_rolls_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.led_roll_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  roll_id bigint NOT NULL,
  path text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['cover'::text, 'gallery'::text, 'tech'::text, 'datasheet'::text, 'installation'::text])),
  alt_text text,
  display_order smallint DEFAULT 100,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT led_roll_media_pkey PRIMARY KEY (id),
  CONSTRAINT led_roll_media_roll_id_fkey FOREIGN KEY (roll_id) REFERENCES public.led_rolls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.led_roll_models (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  roll_id bigint NOT NULL,
  sku text NOT NULL UNIQUE,
  name text,
  description text,
  watt_per_m numeric NOT NULL,
  leds_per_m integer NOT NULL,
  luminous_efficacy_lm_w numeric,
  luminous_flux_per_m_lm numeric,
  cut_step_mm integer,
  width_mm numeric,
  ip_rating text,
  voltage_v integer,
  dimmable boolean,
  cri integer,
  color_mode text NOT NULL,
  light_tone_id bigint,
  cct_min_k integer,
  cct_max_k integer,
  price numeric,
  stock integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT led_roll_models_pkey PRIMARY KEY (id),
  CONSTRAINT led_roll_models_roll_id_fkey FOREIGN KEY (roll_id) REFERENCES public.led_rolls(id) ON DELETE CASCADE,
  CONSTRAINT led_roll_models_light_tone_id_fkey FOREIGN KEY (light_tone_id) REFERENCES public.light_tones(id) ON DELETE SET NULL
);

-------------------------------------------------------------------------------
-- PRODUCTS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  category_id bigint NOT NULL,
  description text,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  product_id bigint NOT NULL,
  variant_code text UNIQUE,
  name text NOT NULL,
  includes_led boolean,
  includes_driver boolean,
  cantidad integer,
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_finishes (
  product_id bigint NOT NULL,
  finish_id bigint NOT NULL,
  CONSTRAINT product_finishes_pkey PRIMARY KEY (product_id, finish_id),
  CONSTRAINT product_finishes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE,
  CONSTRAINT product_finishes_finish_id_fkey FOREIGN KEY (finish_id) REFERENCES public.finishes(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- MEDIA ASSETS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.media_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  product_id bigint,
  variant_id bigint,
  path text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['cover'::text, 'gallery'::text, 'tech'::text, 'datasheet'::text, 'spec'::text])),
  alt_text text,
  created_at timestamp with time zone DEFAULT now(),
  mime_type text,
  file_size_bytes bigint,
  title text,
  CONSTRAINT media_assets_pkey PRIMARY KEY (id),
  CONSTRAINT media_assets_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE,
  CONSTRAINT media_assets_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- FEATURED ITEMS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.featured_items (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  title character varying NOT NULL,
  image_url text NOT NULL,
  link_url text,
  display_order smallint NOT NULL DEFAULT 1 CHECK (display_order >= 1 AND display_order <= 3),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  product_code character varying,
  CONSTRAINT featured_items_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- VARIANT CONFIGURATIONS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.variant_configurations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  variant_id bigint NOT NULL,
  sku text UNIQUE,
  watt numeric NOT NULL,
  lumens integer NOT NULL,
  diameter_description text,
  length_mm numeric,
  width_mm numeric,
  voltage integer,
  specs jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT variant_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT variant_configurations_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- VARIANT LIGHT TONES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.variant_light_tones (
  variant_id bigint NOT NULL,
  light_tone_id bigint NOT NULL,
  CONSTRAINT variant_light_tones_pkey PRIMARY KEY (variant_id, light_tone_id),
  CONSTRAINT variant_light_tones_light_tone_id_fkey FOREIGN KEY (light_tone_id) REFERENCES public.light_tones(id) ON DELETE CASCADE,
  CONSTRAINT variant_light_tones_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- SEARCH LOGS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.search_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  query text NOT NULL,
  results_count integer DEFAULT 0,
  top_similarity double precision,
  execution_time_ms integer,
  user_ip text,
  user_agent text,
  source text DEFAULT 'web'::text,
  created_at timestamp without time zone DEFAULT now(),
  results_ids bigint[],
  user_clicked_product_id bigint,
  user_feedback text CHECK (user_feedback = ANY (ARRAY['helpful'::text, 'not_helpful'::text])),
  feedback_at timestamp without time zone,
  CONSTRAINT search_logs_pkey PRIMARY KEY (id),
  CONSTRAINT search_logs_user_clicked_product_id_fkey FOREIGN KEY (user_clicked_product_id) REFERENCES public.products(id) ON DELETE SET NULL
);

-------------------------------------------------------------------------------
-- USER PROFILES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  display_name text,
  bio text,
  phone text,
  avatar_url text,
  facebook_url text,
  twitter_url text,
  linkedin_url text,
  instagram_url text,
  country text,
  city_state text,
  postal_code text,
  tax_id text,
  full_address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id)
  -- La foreign key a auth.users se agregará después de la migración
  -- CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-------------------------------------------------------------------------------
-- DISTRIBUTOR ZONES
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.distributor_zones (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL UNIQUE,
  display_order integer DEFAULT 100,
  created_at timestamp with time zone DEFAULT NOW(),
  updated_at timestamp with time zone DEFAULT NOW(),
  CONSTRAINT distributor_zones_pkey PRIMARY KEY (id)
);

-------------------------------------------------------------------------------
-- DISTRIBUTORS
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.distributors (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  zone_id bigint NOT NULL,
  name text NOT NULL,
  address text NOT NULL,
  locality text NOT NULL,
  province text,
  postal_code text,
  phone text,
  google_maps_url text,
  email text,
  website text,
  contact_person text,
  notes text,
  active boolean DEFAULT true,
  display_order integer DEFAULT 100,
  created_at timestamp with time zone DEFAULT NOW(),
  updated_at timestamp with time zone DEFAULT NOW(),
  CONSTRAINT distributors_pkey PRIMARY KEY (id),
  CONSTRAINT distributors_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.distributor_zones(id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- INDICES
-------------------------------------------------------------------------------

-- Products
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON public.products(is_featured);
CREATE INDEX IF NOT EXISTS idx_products_code ON public.products(code);

-- Product Variants
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants(product_id);

-- LED Profiles
CREATE INDEX IF NOT EXISTS idx_led_profiles_code ON public.led_profiles(code);
CREATE INDEX IF NOT EXISTS idx_led_profile_media_profile_id ON public.led_profile_media(profile_id);

-- LED Rolls
CREATE INDEX IF NOT EXISTS idx_led_rolls_code ON public.led_rolls(code);
CREATE INDEX IF NOT EXISTS idx_led_roll_models_roll_id ON public.led_roll_models(roll_id);
CREATE INDEX IF NOT EXISTS idx_led_roll_models_light_tone_id ON public.led_roll_models(light_tone_id);

-- Accessories
CREATE INDEX IF NOT EXISTS idx_accessories_code ON public.accessories(code);
CREATE INDEX IF NOT EXISTS idx_accessory_media_accessory_id ON public.accessory_media(accessory_id);

-- Media Assets
CREATE INDEX IF NOT EXISTS idx_media_assets_product_id ON public.media_assets(product_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_variant_id ON public.media_assets(variant_id);

-- Distributors
CREATE INDEX IF NOT EXISTS idx_distributors_zone_id ON public.distributors(zone_id);
CREATE INDEX IF NOT EXISTS idx_distributors_active ON public.distributors(active);

-- Search Logs
CREATE INDEX IF NOT EXISTS idx_search_logs_created_at ON public.search_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_search_logs_query ON public.search_logs USING gin(query gin_trgm_ops);

-------------------------------------------------------------------------------
-- DATOS INICIALES: distributor_zones
-------------------------------------------------------------------------------
INSERT INTO public.distributor_zones (name, display_order) VALUES
  ('GBA OESTE', 1),
  ('GBA SUR', 2),
  ('MENDOZA', 3),
  ('NEUQUÉN', 4)
ON CONFLICT (name) DO NOTHING;

-------------------------------------------------------------------------------
-- COMENTARIOS
-------------------------------------------------------------------------------
COMMENT ON TABLE public.categories IS 'Categorías de productos';
COMMENT ON TABLE public.finishes IS 'Acabados/terminaciones disponibles';
COMMENT ON TABLE public.light_tones IS 'Tonos de luz (kelvin)';
COMMENT ON TABLE public.accessories IS 'Accesorios y complementos';
COMMENT ON TABLE public.led_diffusers IS 'Difusores para perfiles LED';
COMMENT ON TABLE public.led_profiles IS 'Perfiles LED con especificaciones';
COMMENT ON TABLE public.led_rolls IS 'Tiras/rollos LED';
COMMENT ON TABLE public.led_roll_models IS 'Modelos específicos de tiras LED';
COMMENT ON TABLE public.products IS 'Productos principales del catálogo';
COMMENT ON TABLE public.product_variants IS 'Variantes de productos';
COMMENT ON TABLE public.media_assets IS 'Archivos multimedia de productos/variantes';
COMMENT ON TABLE public.featured_items IS 'Items destacados en la home';
COMMENT ON TABLE public.search_logs IS 'Logs de búsquedas de usuarios';
COMMENT ON TABLE public.distributor_zones IS 'Zonas geográficas de distribución';
COMMENT ON TABLE public.distributors IS 'Distribuidores autorizados';

-------------------------------------------------------------------------------
-- FIN DEL SCHEMA
-------------------------------------------------------------------------------
