-- =============================================
-- MIGRACIÓN: Fuentes LED (power supplies)
-- Familia (ej. "Ultra Slim 36W") → modelos por voltaje de salida (12V / 24V)
-- =============================================

CREATE TABLE IF NOT EXISTS public.power_supplies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,                 -- ej: GSG-36WHH
  name text NOT NULL,                        -- ej: Fuente Ultra Slim 36W
  series text,                               -- ej: Ultra Slim | Slim
  description text,
  power_w numeric,                           -- potencia nominal
  ip_rating text,                            -- ej: IP20
  length_mm numeric,
  width_mm numeric,
  height_mm numeric,
  warranty_years integer,
  connection text,                           -- ej: Bornera PUSH
  dimmable boolean DEFAULT false,            -- regulación por DIP switch
  dimming_notes text,                        -- ej: 4 niveles (25/50/75/100 %)
  notes text,                                -- ej: trabajar hasta el 80% de la potencia nominal
  photo_url text,                            -- imagen principal
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.power_supply_models (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  power_supply_id bigint NOT NULL REFERENCES public.power_supplies(id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,                 -- ej: GSG-36WHH-12
  input_v_min integer,                       -- ej: 100
  input_v_max integer,                       -- ej: 264
  input_label text,                          -- ej: 100 - 264 VAC
  output_v numeric NOT NULL,                 -- ej: 12
  current_a numeric,                         -- ej: 3
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.power_supply_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  power_supply_id bigint NOT NULL REFERENCES public.power_supplies(id) ON DELETE CASCADE,
  path text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['gallery'::text, 'tech'::text, 'datasheet'::text])),
  alt_text text,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_power_supply_models_ps ON public.power_supply_models(power_supply_id);
CREATE INDEX IF NOT EXISTS idx_power_supply_media_ps ON public.power_supply_media(power_supply_id);

-- RLS: lectura pública, escritura solo service_role (API del backoffice)
ALTER TABLE public.power_supplies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.power_supply_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.power_supply_media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "power_supplies_select_public" ON public.power_supplies;
CREATE POLICY "power_supplies_select_public" ON public.power_supplies FOR SELECT USING (true);
DROP POLICY IF EXISTS "power_supply_models_select_public" ON public.power_supply_models;
CREATE POLICY "power_supply_models_select_public" ON public.power_supply_models FOR SELECT USING (true);
DROP POLICY IF EXISTS "power_supply_media_select_public" ON public.power_supply_media;
CREATE POLICY "power_supply_media_select_public" ON public.power_supply_media FOR SELECT USING (true);

DROP POLICY IF EXISTS "power_supplies_write_service_role" ON public.power_supplies;
CREATE POLICY "power_supplies_write_service_role" ON public.power_supplies
  FOR ALL USING (auth.jwt()->>'role' = 'service_role') WITH CHECK (auth.jwt()->>'role' = 'service_role');
DROP POLICY IF EXISTS "power_supply_models_write_service_role" ON public.power_supply_models;
CREATE POLICY "power_supply_models_write_service_role" ON public.power_supply_models
  FOR ALL USING (auth.jwt()->>'role' = 'service_role') WITH CHECK (auth.jwt()->>'role' = 'service_role');
DROP POLICY IF EXISTS "power_supply_media_write_service_role" ON public.power_supply_media;
CREATE POLICY "power_supply_media_write_service_role" ON public.power_supply_media
  FOR ALL USING (auth.jwt()->>'role' = 'service_role') WITH CHECK (auth.jwt()->>'role' = 'service_role');
